---
- name: Enabling GNOME Shell top left hot corner
  pacman: name=gnome-shell-extension-no-topleft-hot-corner state=absent
  when: "not gnome.gnome_shell.disable_top_left_hot_corner"

- name: Configuring GNOME Shell Extensions support
  pacman:
    name:
      - gnome-shell-extensions
      - chrome-gnome-shell
    state: "{{ 'present' if gnome.gnome_shell.extensions_support else 'absent' }}"
